// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcy70OVYIId2n9c-LC2wehgAl5PSRFKUE',
    appId: '1:333981208935:web:2dfdeb22f1b034db339fc2',
    messagingSenderId: '333981208935',
    projectId: 'take-note-644af',
    authDomain: 'take-note-644af.firebaseapp.com',
    storageBucket: 'take-note-644af.firebasestorage.app',
    measurementId: 'G-T6869YL23C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCNQ6qHl2G2swT3WA7urTFD6lTxkVwyMjM',
    appId: '1:333981208935:android:74519a7ef9d5c2ef339fc2',
    messagingSenderId: '333981208935',
    projectId: 'take-note-644af',
    storageBucket: 'take-note-644af.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBd5DDcwildd8u3hhXMa8XoTGWsQgHkkQU',
    appId: '1:333981208935:ios:30c0c3eb25d05a5c339fc2',
    messagingSenderId: '333981208935',
    projectId: 'take-note-644af',
    storageBucket: 'take-note-644af.firebasestorage.app',
    iosBundleId: 'com.example.takeNote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBd5DDcwildd8u3hhXMa8XoTGWsQgHkkQU',
    appId: '1:333981208935:ios:30c0c3eb25d05a5c339fc2',
    messagingSenderId: '333981208935',
    projectId: 'take-note-644af',
    storageBucket: 'take-note-644af.firebasestorage.app',
    iosBundleId: 'com.example.takeNote',
  );
}
